### ISSUE TITLE
All constructor argument types must model ParameterConcept

### ISSUE THREAD

**Issue by tkaplan** [arun11299/cpp-jwt#10]
Hi I'm trying to just extract a string value from my jwt token...

```
auto jwt = jwt_t.payload();
string value = jwt.get_claim_value<string>("key");
```

But it throws the error above. How am I suppose to work with raw values?

**Comment by arun11299** [comment]
@tkaplan 
Could you provide an example ? Or have you solved this issue yourself ? It seems you may be using the API incorrectly.
