### ISSUE TITLE
Compilation error on VS2017

### ISSUE THREAD

**Issue by sarbjit-longia** [arun11299/cpp-jwt#11]
Getting compilation error while using the library on windows using vs2017

cpp-jwt-master\include\jwt\detail\meta.hpp(229): error C3520: 'T': parameter pack must be expanded in this context
cpp-jwt-master\include\jwt\impl\jwt.ipp(300): error C2600: 'jwt::jwt_object::jwt_object': cannot define a compiler-generated special member function (must be declared in the class first)

**Comment by arun11299** [comment]
Hi,
Thanks for reporting. I have fixed the issue. Please do let me know if you face any other issue.

**Comment by sarbjit-longia** [comment]
Thanks for fixing this issue. I just tested it and the issue for  error C2600: 'jwt::jwt_object::jwt_object': cannot define a compiler-generated special member function (must be declared in the class first) still remains, so logging another issue.
