### ISSUE TITLE
Expects the two arrays in file base64.cpp to be in double curly braces on Linux.

### ISSUE THREAD

**Issue by sarbjit-longia** [arun11299/cpp-jwt#13]
https://github.com/arun11299/cpp-jwt/blob/9ddaa092cb2e989d88daea16c877a201be0b2258/include/jwt/base64.hpp#L68

Array on Line 161
Array on line 68

**Comment by arun11299** [comment]
Fixed with commit 2cb65f231a0df5292eda2b997bb76c10dab26613

**Comment by sarbjit-longia** [comment]
Thanks :)
