### ISSUE TITLE
Some tests don't pass

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [arun11299/cpp-jwt#14]
Two tests don't pass. Please take a look:

First:
```
FAIL    DecodeVerify.ValidIssuerTest
./cpp-jwt/tests/test_jwt_decode_verifiy.cc:75: Failure
Value of: ec
  Actual: true
Expected: false
```
The second:
```
FAIL    DecodeVerifyExp.ValidIssuerTest
unknown file: Failure
C++ exception with description "invalid issuer" thrown in the test body.
```
Both seem to be the same but with two versions, with and without exception.

How serious is this? Is there something I can do to fix this?

I'm on Ubuntu 16.04.

**Comment by arun11299** [comment]
Thanks for reporting.
I have fixed the issue. Can you take the latest clone and confirm ?

Thanks,

**Comment by TheQuantumPhysicist** [comment]
Yep! That fixes the issue! Thanks a lot for the fast response (and for the professional testing provided).

Cheers!
