### ISSUE TITLE
When will you generate a release (github one)?

### ISSUE THREAD

**Issue by handicraftsman** [arun11299/cpp-jwt#2]

**Comment by arun11299** [comment]
Hello,
I have not done release management to any of my repositories :)
I have though created a pull request for this library to be included in the main jsonwebtoken repository and will take some time to get accepted.
If you think it would be useful to have a release version for this library, then I will certainly look into that.

Thanks!

**Comment by DEGoodmanWilson** [comment]
Hello! Seconded for the version tagging. I'm building a conan package for this library, and it would be lovely if that package could be versioned rather than always building off of master.

**Comment by arun11299** [comment]
Hello @DEGoodmanWilson 
I have just created a release v1.0. Let me know if that works for you.

Thanks !!

**Comment by DEGoodmanWilson** [comment]
Awesome, thank you!

Could I perhaps push you a little, and convince you of the virtues of [SemVer](https://semver.org/)?

**Comment by DEGoodmanWilson** [comment]
Apologies, it looks like the tag you created didn't make it up to GitHub—I can't see it 😞

**Comment by arun11299** [comment]
@DEGoodmanWilson 
Gosh...I released another library cpp-subprocess instead of cpp-jwt.

**Comment by arun11299** [comment]
@DEGoodmanWilson 
Done now for sure. 
As for SemVer, I need to do some reading on that. Could you create an issue if you think that would be useful ?


Thanks a lot!
