### ISSUE TITLE
Why does the existence of a signature algorithm entail a required verification?

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [arun11299/cpp-jwt#24]
In my code, I have parts where I need to extract the data from a token without verifying it (and without the key being available). Basically because the verification was done before and the token was authorized.

Now check out this part of the code:

https://github.com/arun11299/cpp-jwt/blob/077e6f3f07ec113d2ae24384d1b10870c059d04d/include/jwt/impl/jwt.ipp#L698

In line 698, the code gets the message from the user that a verification is not necessary, so that block is skipped. But then in line 709, this block completely ignores whether the user wants to verify, and simply checks the header and whether there's an algorithm associated with the header. This basically means that it's **impossible** to extract information from a token **without** a key. For me, I'm getting an error code `DecodeErrc::KeyNotPresent`, because there's no key associated with the object, although I'm not willing to verify.

The fix I suggest is to put this block inside the other block in line 698. Only if the user is willing to verify, then the algorithm should be checked.

The reason I haven't created a pull-request for this is that I'm not sure why this was done this way, and there's the possibility that there's something I'm misunderstanding here. So kindly explain whether my reasoning is correct.

Best.

**Comment by arun11299** [comment]
How about using "NONE" algorithm for such cases ? Setting an algorithm and not using a key does not sound a realistic scenario to me.

**Comment by TheQuantumPhysicist** [comment]
The thing is that the token is already there. It's not my choice of what algorithm goes into the token anymore. What I'd like to do is just decode an existing token. You're assuming that the dev who wants to extract contents from a token also has the power to decide the algorithm, which is not generally the case, unless one has to tamper with the token before extracting data from it. Also remember that verification costs computation that may not be necessary depending on the application.

What puzzles me in all this is: Why is it OK to ignore the dev's will to verify? Isn't that the point of having the parameter `params::verify(false)`? Is there something I'm missing here?

**Comment by arun11299** [comment]
So the payload of the token anyways cannot be decided without the key. But the user can still get the decoded header which is the only thing that can be decided in this case.

**Comment by TheQuantumPhysicist** [comment]
I feel what you said is a little ambiguous, but I guess my answer is yes. That's the situation. In the current state, the payload is unreachable through the API if no key was set, and in general, why is someone who wants to read the payload required to enter a key? I don't understand this.

Please remember that the payload is not encrypted. So decoding has nothing to do with the key being present. The algorithm is just for the signature.

**Comment by arun11299** [comment]
Payload is also available in decoded form in the object. Sorry I missed that.

**Comment by arun11299** [comment]
I will provide a fix to not do the signature verification.

**Comment by TheQuantumPhysicist** [comment]
Please review my suggestion on how to fix this. It costs literally nothing. Just a cut and paste.

**Comment by arun11299** [comment]
@TheQuantumPhysicist Sorry I accidentally deleted your comment instead of mine and I dont know how to undo. Can you please add it back ? Really sorry for that.

**Comment by TheQuantumPhysicist** [comment]
I was just suggesting that you review my suggestion on how to fix this. It just costs a copy and paste.

**Comment by arun11299** [comment]
Yes thats what needs to be done. I have few tests to fix which depended on that.
