### ISSUE TITLE
Building example code fails

### ISSUE THREAD

**Issue by DEGoodmanWilson** [arun11299/cpp-jwt#3]
Hello! I'm running into issues compiling the example code near the top of the readme.
System information: OS X 10.13.3, clang Apple LLVM version 9.0.0 (clang-900.0.39.2)

I get a series of errors, all variants on the same thing: Member access into incomplete types:

```
In file included from /Users/dgoodman/Documents/Projects/silverstar/main.cpp:22:
In file included from /Users/dgoodman/.conan/data/cpp-jwt/0.1.0/DEGoodmanWilson/testing/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/jwt/jwt.hpp:35:
/Users/dgoodman/.conan/data/cpp-jwt/0.1.0/DEGoodmanWilson/testing/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/jwt/algorithm.hpp:520:33: error: member access into incomplete type 'const ECDSA_SIG' (aka 'const ECDSA_SIG_st')
    if (pr != nullptr) *pr = sig->r;
                                ^
```

I'm building against openssl 1.1.0g, installed via Conan (hence the crazy paths above).

**Comment by arun11299** [comment]
Hello @DEGoodmanWilson 
Thanks for trying it out.
I have tested this library only against OpenSSL version "1.0.2j". Would it be possible for you to upgrade  as well ?

**Comment by DEGoodmanWilson** [comment]
Unfortunately, `1.0.2j` is a downgrade from the `1.1.0x` series—not an upgrade. Unfortunately, my own code relies on newer versions of OpenSSL so downgrading isn't an option for me personally. It might be for others though.

**Comment by DEGoodmanWilson** [comment]
(If you read my deleted comment, ignore it). It looks like this is no problem at all! I'm going to move to a slightly newer version `1.0.2n`. (Also, `1.0.2x` is a _downgrade_ from `1.1.0x`, FWIW, not an upgrade.. But everything I'm using depends on `1.0.2x` so it's fine with me!)
