### ISSUE TITLE
Move semantics

### ISSUE THREAD

**Issue by mhfrantz** [arun11299/cpp-jwt#33]
It would be nice if `jwt_object` supported move semantics:
```c++
jwt_object(jwt_object&&);
jwt_object& operator=(jwt_object&&);
```
If this is acceptable, I can provide a PR.

**Comment by arun11299** [comment]
Thanks. Is it not already ? I think all the members are move assignable and move copyable. Thus by "rule-of-zero" jwt_object should be too. Maybe defaulting it explicitly is a good way.

**Comment by mhfrantz** [comment]
I think the problem is that by not declaring them, the template constructor is a "universal reference" which is preferred by the compiler over the automatically generated one. When I tried to use the move constructor, my compiler (GCC 7.3) tried to use this one instead:
```c++
  template <typename First, typename... Rest>
  jwt_object(First&& first, Rest&&... rest);
```
Then it failed because `jwt_object` does not model the parameter concept.

**Comment by arun11299** [comment]
Ah..ok. Thanks.
Please provide a PR so that I can merge those changes.

**Comment by arun11299** [comment]
This is already addressed in another PR
