### ISSUE TITLE
Narrowing errors compiling for ARM

### ISSUE THREAD

**Issue by mhfrantz** [arun11299/cpp-jwt#36]
When compiling for ARM, we get errors like this:
```
cpp-jwt/include/jwt/base64.hpp:179:4: error: narrowing conversion of ‘-1’ from ‘int’ to ‘char’ inside { } [-Wnarrowing]
```
The issue is described here: https://stackoverflow.com/questions/31634962/narrowing-conversion-from-int-to-char-inside-for-legal-values-when-cro

The solution is to use `signed char` in places where you want to make sure the values are interpreted as signed integers.

**Comment by arun11299** [comment]
Thanks. Fixed it.
