### ISSUE TITLE
Use SemVer for versioning

### ISSUE THREAD

**Issue by DEGoodmanWilson** [arun11299/cpp-jwt#4]
Use [SemVer](https://semver.org/) for versioning. SemVer is designed to help developers and systems to consume dependencies make informed and automated decisions about which version of a dependecy tonuse, by encoding the nature of API changes into the structure of the version number. It’s super useful for package managers like Conan, so developers can create policies stipulating when—and when not—to upgrade a dependency.

Examples:
1.0.0 — first production-ready release
1.0.1 — bugfix or security patch not affecting API. Upgrading recommended or mandatory. Downgrading possible but not recommended. 
1.1.0 — new feature that extends API without changing existing API. Upgrading recommended or encouraged. Downgrading may or may not be possible depending on whether te new feature is being used. 
2.0.0 — Breaking change to API that will cause exiting projects to fail compilation without changes. Upgrading optional. Downgrading likely impossible.

**Comment by arun11299** [comment]
@DEGoodmanWilson 
If I have understood it correct, I am using semantic versioning now.
Released latest 1.0.1 !

**Comment by DEGoodmanWilson** [comment]
🙌
