### ISSUE TITLE
verify list in audience claim

### ISSUE THREAD

**Issue by XM37** [arun11299/cpp-jwt#44]
Hi,

i will verify an item inside the audience claim. How can i do this?

A short example:

```
"aud": [
    "normal_user",
    "https://dev.eu.auth0.com/userinfo"
  ],
```

how can i verify one of these items inside the JWT token?

I have following decoding statement in my code:
`jwt::decode(token, jwt::params::algorithms({algorithm}), jwt::params::aud("normal_user"), jwt::params::secret(key), jwt::params::verify(true));`

But if I run these piece of code I will receive following error code:  
> type conversion error

**Comment by arun11299** [comment]
Will take a look at it tomorrow.

**Comment by arun11299** [comment]
Hi,
I am not able to reproduce the same issue. There seems to be issue with your JSON data types. An example being the "InvalidIATTest" test.

Can you give me a complete example ?

Thanks.

**Comment by arun11299** [comment]
@XM37 Is it still an issue ?
