### ISSUE TITLE
Thread Safe

### ISSUE THREAD

**Issue by webfolderio** [arun11299/cpp-jwt#45]
hi,

is this library thread safe? If yes which methods? Verify, generate etc...

**Comment by arun11299** [comment]
H i @webfolderio 
This library does not assume anything about thread safety. So, I would say that it is as thread safe as an std::vector.
Since the library uses OpenSSL, it would be better to make sure that you call verify/sign/decode under a mutex.

**Comment by webfolderio** [comment]
Thanks for the clarification.
