### ISSUE TITLE
Openssl make does not work

### ISSUE THREAD

**Issue by tkaplan** [arun11299/cpp-jwt#5]
This seems to be a big problem with a lot of other projects so I'm surprised it hasn't been reported here yet.

I'm getting make errors like so...
```

/usr/include/openssl/ec.h:1039:16: note: forward declaration of 'ECDSA_SIG {aka struct ECDSA_SIG_st}'
 typedef struct ECDSA_SIG_st ECDSA_SIG;
```

Is there a fix for this?

**Comment by arun11299** [comment]
Hello,
Thanks for reporting.
Can you tell me which openssl version are you using. The library has been tested only with 1.0.2j version.
Also, it would be helpful if you can paste the commands you are using to build.

Thanks.

**Comment by arun11299** [comment]
Also, I know few people who are actually using this library, but have not faced this issue.

**Comment by DEGoodmanWilson** [comment]
I encountered this issues too in #3 . Looks like you're using openssl 1.1.0, which isn't compatible. You'll need to use openssl 1.0.2.

**Comment by arun11299** [comment]
@tkaplan @DEGoodmanWilson I could reproduce the issue using latest openssl version. From google search it seems that it has broken builds of quite a lot of libraries.
I will provide a fix for it soon.

Thanks.

**Comment by arun11299** [comment]
@tkaplan @DEGoodmanWilson 
I have pushed the changes for the referenced errors. Let me know if you still see the issues with the openssl version that you are using.

Thanks.
