### ISSUE TITLE
Deprecated BIO_f_base64 from boringssl

### ISSUE THREAD

**Issue by gramic** [arun11299/cpp-jwt#61]
The BIO_f_base64 is deprecated in boringssl.
The function is used in the [ include/jwt/impl/algorithm.ipp][1].

Isn't it better to use your own [base64] functionality instead?

[1]: https://github.com/arun11299/cpp-jwt/blob/87dcef903f48a8c33df0bd9658d775d6d5db1918/include/jwt/impl/algorithm.ipp#L36
[base64]: https://github.com/arun11299/cpp-jwt/blob/master/include/jwt/base64.hpp

**Comment by arun11299** [comment]
Thanks for reporting. I will take a look at it.

**Comment by chenboy3** [comment]
Hi, also running into this issue, are there any updates on this issue?

**Comment by arun11299** [comment]
Hell @chenboy3 @gramic 
I have verified the fix with the existing tests. It would be great if you could verify the same.

Thanks.

**Comment by chenboy3** [comment]
Works for me, thanks again!
