### ISSUE TITLE
Need help with decoding jwt

### ISSUE THREAD

**Issue by Boomslangnz** [arun11299/cpp-jwt#71]
Hi there, 

I am new at trying to decode jwt etc and have made a node.js api which im sending back json to a c++ program.

I must be doing something wrong as I want to encrypt the jwt from node.js and decrypt it on c++ using cpp-jwt

But what im finding is I recieve the encrypted jwt on c++ and decrypting doesn't seem to occur at all even if using correct key etc, it stays encrypted after.

Any suggestions to try at all? ive been at this for so many hours lol

**Comment by arun11299** [comment]
Hello @Boomslangnz 
My suggestion to create a reproducible example:
1. Capture the JSON string being sent to C++ server.
2. Create a test C++ decoder program as shown in the many test files in the repo.

If you still have trouble with the test, then please share the test code here and we will see.

**Comment by Boomslangnz** [comment]
Thanks alot for the reply. I worked out my issue in the end and successfully decoded 👍 

Great work
