### ISSUE TITLE
OpenSSL 1.1.1 without libressl causes issue

### ISSUE THREAD

**Issue by williamswhy** [arun11299/cpp-jwt#77]
I think there is an issue in this line of code
```
#if OPENSSL_VERSION_NUMBER < 0x10100000L || LIBRESSL_VERSION_NUMBER < 0x20700000L
```
I don't have libressl installed so `LIBRESSL_VERSION_NUMBER` for me is undefined. In this case, the second half of the if statement is always true.
I am using openssl-1.1.1f. The code will not compile due to this.

Currently, I manually define the libressl version in cmake as a workaround
```
add_definitions(-DLIBRESSL_VERSION_NUMBER=0x20700000L)
```

**Comment by arun11299** [comment]
Hello @williamswhy 
Can we close this if your patch addresses this issue ?

**Comment by williamswhy** [comment]
I actually think #75 is the correct patch

**Comment by williamswhy** [comment]
Issue resolved! Thank you!
