### ISSUE TITLE
Fix tests to compile

### ISSUE THREAD

**Issue by gramic** [arun11299/cpp-jwt#9]
Currently at least test_jwt_decode.cc has errors.
I am able to fix them, but it was suspicious to find that they do not compile. Are you plannig to keep them working?

**Comment by arun11299** [comment]
Hello @gramic 
Can you give some more information about the failure ? Specifically:
1. Compile time errors
2. Platform
3. OpenSSL version

Thanks.

**Comment by gramic** [comment]
I did not provide the error because it is too simple. However, here it is

`include/jwt/test/test_jwt_decode.cc:17:32: error: too few arguments to function call, expected 3, have 2
  auto res = sgn.encode(hdr, jp);`

**Comment by arun11299** [comment]
Ah...I see it now. These are internal tests that I was using while developing it. I didn't think anybody would use these instead of the tests which are there outside the include directory.

I will fix these. Thanks for reporting.

**Comment by gramic** [comment]
Well, I really did intent to use those outside, but somehow I made a mistake too.
